/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "blackbox_data.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>

#include "logger.h"

#ifndef SIG_PF
#define SIG_PF void (*)(int)
#endif

static void
blackbox_data_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union
	{
		blackbox_run_info run_blackbox_1_arg;
		blackbox_part_info send_blackbox_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc)
	{
	case NULLPROC:
		(void)svc_sendreply(transp, (xdrproc_t)xdr_void, (char *)NULL);
		return;

	case RUN_BLACKBOX:
		_xdr_argument = (xdrproc_t)xdr_blackbox_run_info;
		_xdr_result = (xdrproc_t)xdr_blackbox_response;
		local = (char *(*)(char *, struct svc_req *))run_blackbox_1_svc;
		break;

	case SEND_BLACKBOX:
		_xdr_argument = (xdrproc_t)xdr_blackbox_part_info;
		_xdr_result = (xdrproc_t)xdr_int;
		local = (char *(*)(char *, struct svc_req *))send_blackbox_1_svc;
		break;

	default:
		svcerr_noproc(transp);
		return;
	}
	memset((char *)&argument, 0, sizeof(argument));
	if (!svc_getargs(transp, (xdrproc_t)_xdr_argument, (caddr_t)&argument))
	{
		svcerr_decode(transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t)_xdr_result, result))
	{
		svcerr_systemerr(transp);
	}
	if (!svc_freeargs(transp, (xdrproc_t)_xdr_argument, (caddr_t)&argument))
	{
		fprintf(stderr, "%s", "unable to free arguments");
		exit(1);
	}
	return;
}

static void sig_handler(int signo)
{
	if (signo == SIGTSTP)
	{
		printf("[SERVER] Terminating the server ...\n");
		exit(EXIT_SUCCESS);
	}
}

int main(int argc, char **argv)
{

	//////////////////////////// EDIT BEGIN ///////////////////////////////
	printf("[SERVER] Starting blackbox runner server ...\n");

	if (argc != 3)
	{
		printf("[SERVER][ERROR] Number of arguments are wrong.Use <logger_server_name> <logger_server_port_number>\n");
		exit(1);
	}

	if (signal(SIGTSTP, sig_handler) == SIG_ERR)
	{
		printf("[SERVER][ERROR] Setting up signal handler\n");
		exit(1);
	}

	const char *p_logger_server_name = argv[1];
	unsigned int logger_server_port_number = strtol(argv[2], NULL, 10);

	logger_set_server_info(p_logger_server_name, logger_server_port_number);

	//////////////////////////// EDIT END /////////////////////////////////

	register SVCXPRT *transp;

	pmap_unset(BLACKBOX_DATA, BLACKBOX_DATA_V1);

	transp = svcudp_create(RPC_ANYSOCK);
	if (transp == NULL)
	{
		fprintf(stderr, "%s", "cannot create udp service.");
		exit(1);
	}
	if (!svc_register(transp, BLACKBOX_DATA, BLACKBOX_DATA_V1, blackbox_data_1, IPPROTO_UDP))
	{
		fprintf(stderr, "%s", "unable to register (BLACKBOX_DATA, BLACKBOX_DATA_V1, udp).");
		exit(1);
	}

	transp = svctcp_create(RPC_ANYSOCK, 0, 0);
	if (transp == NULL)
	{
		fprintf(stderr, "%s", "cannot create tcp service.");
		exit(1);
	}
	if (!svc_register(transp, BLACKBOX_DATA, BLACKBOX_DATA_V1, blackbox_data_1, IPPROTO_TCP))
	{
		fprintf(stderr, "%s", "unable to register (BLACKBOX_DATA, BLACKBOX_DATA_V1, tcp).");
		exit(1);
	}

	svc_run();
	fprintf(stderr, "%s", "svc_run returned");
	exit(1);
	/* NOTREACHED */
}
