/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "logger_data.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>
#include <arpa/inet.h>
#include <signal.h>

//////////////////////////////////////// EDITED AUTO-GEN FILE /////////////////////////////
#include <rpc/rpc.h>
#include "logger_server.h"

//////////////////////////////////////// EDITED AUTO-GEN FILE /////////////////////////////

#ifndef SIG_PF
#define SIG_PF void (*)(int)
#endif

static void
logger_data_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union
	{
		logger_info save_log_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc)
	{
	case NULLPROC:
		(void)svc_sendreply(transp, (xdrproc_t)xdr_void, (char *)NULL);
		return;

	case SAVE_LOG:
		_xdr_argument = (xdrproc_t)xdr_logger_info;
		_xdr_result = (xdrproc_t)xdr_int;
		local = (char *(*)(char *, struct svc_req *))save_log_1_svc;
		break;

	default:
		svcerr_noproc(transp);
		return;
	}
	memset((char *)&argument, 0, sizeof(argument));
	if (!svc_getargs(transp, (xdrproc_t)_xdr_argument, (caddr_t)&argument))
	{
		svcerr_decode(transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t)_xdr_result, result))
	{
		svcerr_systemerr(transp);
	}
	if (!svc_freeargs(transp, (xdrproc_t)_xdr_argument, (caddr_t)&argument))
	{
		fprintf(stderr, "%s", "unable to free arguments");
		exit(1);
	}
	return;
}

static void sig_handler(int signo)
{
	if (signo == SIGTSTP)
	{
		printf("[LOGGER] Terminating the server ...\n");
		svc_unregister(LOGGER_DATA, LOGGER_DATA_V1);
		pmap_unset(LOGGER_DATA, LOGGER_DATA_V1);
		exit(EXIT_SUCCESS);
	}
}

static int create_socket_binded_with_addr(unsigned short int port_number)
{
	// Create a socket and bind it with an address
	int my_socket;
	if ((my_socket = socket(AF_INET, SOCK_STREAM, 0)) == 0)
	{
		printf("[LOGGER][ERROR] Error socket failed.\n");
		return 0;
	}

	struct sockaddr_in sin;
	sin.sin_family = AF_INET;
	sin.sin_addr.s_addr = htonl(INADDR_ANY);
	sin.sin_port = htons(port_number);

	if ((bind(my_socket, (struct sockaddr *)&sin, sizeof sin)) < 0)
	{
		printf("[LOGGER][ERROR] Error Bind failed.\n");
		return 0;
	}

	return my_socket;
}

static void print_svc_addr(register SVCXPRT *transp)
{

	struct sockaddr_in *my_address = svc_getcaller(transp);
	if (my_address != NULL)
	{
		char ipstr[INET_ADDRSTRLEN];
		void *addr;

		// convert the IP to a string and print it
		if (inet_ntop(AF_INET, &(my_address->sin_addr), ipstr, sizeof(ipstr)) != NULL)
		{
			printf("[LOGGER][INFO] Logger ip addres resolved to : %s\n", ipstr);
			printf("[LOGGER][INFO] Port: %d\n", ntohs(my_address->sin_port));
		}
		else
		{
			printf("[LOGGER][ERROR] inet_ntop\n");
		}
	}
	else
	{
		printf("[LOGGER][INFO] Svc_getcaller\n");
	}
}

int main(int argc, char *argv[])
{
	//////////////////////////////////////// EDIT START /////////////////////////////
	printf("[LOGGER] Starting logger server...\n");

	// Set up signal handler for SIGTSTP
	if (signal(SIGTSTP, sig_handler) == SIG_ERR)
	{
		printf("[LOGGER][ERROR] Error setting up signal handler\n");
		exit(1);
	}

	if (argc != 3)
	{
		printf("[LOGGER] Number of arguments are wrong. Use <logfilename.log> <PORT_NUMBER>\n");
		exit(1);
	}

	const char *log_filename = argv[1];
	const char *port_number_str = argv[2];
	int port_number = strtol(port_number_str, NULL, 10);
	printf("[LOGGER][INFO] Port number argument : %d\n", port_number);

	set_log_file_name(log_filename);

	int binded_socket = create_socket_binded_with_addr(port_number);
	if (0 == binded_socket)
	{
		printf("[LOGGER] Bind failed.\n");
		exit(1);
	}

	//////////////////////////////////////// EDIT END /////////////////////////////

	register SVCXPRT *transp;
	pmap_unset(LOGGER_DATA, LOGGER_DATA_V1);

	transp = svctcp_create(binded_socket, 0, 0);
	if (transp == NULL)
	{
		fprintf(stderr, "%s", "cannot create tcp service.");
		exit(1);
	}

	if (!svc_register(transp, LOGGER_DATA, LOGGER_DATA_V1, logger_data_1, IPPROTO_TCP))
	{
		fprintf(stderr, "%s", "unable to register (LOGGER_DATA, LOGGER_DATA_V1, tcp).");
		exit(1);
	}

	//////////////////////////////////////// EDIT START /////////////////////////////
	// print_svc_addr(transp);
	//////////////////////////////////////// EDIT END /////////////////////////////

	svc_run();

	fprintf(stderr, "%s", "svc_run returned");
	exit(1);
	/* NOTREACHED */
}
