/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "blackbox_data.h"

bool_t
xdr_blackbox_part_info (XDR *xdrs, blackbox_part_info *objp)
{
	register int32_t *buf;


	if (xdrs->x_op == XDR_ENCODE) {
		 if (!xdr_array (xdrs, (char **)&objp->bin_packet.bin_packet_val, (u_int *) &objp->bin_packet.bin_packet_len, 1000,
			sizeof (uint8_t), (xdrproc_t) xdr_uint8_t))
			 return FALSE;
		buf = XDR_INLINE (xdrs, 4 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_u_int (xdrs, &objp->total_size))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->packet_size))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->bin_count))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->transfer_status))
				 return FALSE;
		} else {
			IXDR_PUT_U_LONG(buf, objp->total_size);
			IXDR_PUT_U_LONG(buf, objp->packet_size);
			IXDR_PUT_U_LONG(buf, objp->bin_count);
			IXDR_PUT_LONG(buf, objp->transfer_status);
		}
		return TRUE;
	} else if (xdrs->x_op == XDR_DECODE) {
		 if (!xdr_array (xdrs, (char **)&objp->bin_packet.bin_packet_val, (u_int *) &objp->bin_packet.bin_packet_len, 1000,
			sizeof (uint8_t), (xdrproc_t) xdr_uint8_t))
			 return FALSE;
		buf = XDR_INLINE (xdrs, 4 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_u_int (xdrs, &objp->total_size))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->packet_size))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->bin_count))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->transfer_status))
				 return FALSE;
		} else {
			objp->total_size = IXDR_GET_U_LONG(buf);
			objp->packet_size = IXDR_GET_U_LONG(buf);
			objp->bin_count = IXDR_GET_U_LONG(buf);
			objp->transfer_status = IXDR_GET_LONG(buf);
		}
	 return TRUE;
	}

	 if (!xdr_array (xdrs, (char **)&objp->bin_packet.bin_packet_val, (u_int *) &objp->bin_packet.bin_packet_len, 1000,
		sizeof (uint8_t), (xdrproc_t) xdr_uint8_t))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->total_size))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->packet_size))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->bin_count))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->transfer_status))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_blackbox_run_info (XDR *xdrs, blackbox_run_info *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->input1))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->input2))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_blackbox_response (XDR *xdrs, blackbox_response *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->process_result))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->std_out, 128))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->std_err, 128))
		 return FALSE;
	return TRUE;
}
