/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _LOGGER_DATA_H_RPCGEN
#define _LOGGER_DATA_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct logger_info {
	char *log_string;
};
typedef struct logger_info logger_info;

#define LOGGER_DATA 0x2ffffff1
#define LOGGER_DATA_V1 1

#if defined(__STDC__) || defined(__cplusplus)
#define SAVE_LOG 1
extern  int * save_log_1(logger_info *, CLIENT *);
extern  int * save_log_1_svc(logger_info *, struct svc_req *);
extern int logger_data_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define SAVE_LOG 1
extern  int * save_log_1();
extern  int * save_log_1_svc();
extern int logger_data_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_logger_info (XDR *, logger_info*);

#else /* K&R C */
extern bool_t xdr_logger_info ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_LOGGER_DATA_H_RPCGEN */
